openapi: 3.0.3
info:
  title: Phoenix Control Actuator API
  description: API for the Phoenix PID control service
  version: 1.0.0
servers:
  - url: http://localhost:8081
    description: Local development
paths:
  /health:
    get:
      summary: Health check
      operationId: getHealth
      responses:
        '200':
          description: Service health
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthStatus'
  /metrics:
    get:
      summary: Retrieve control metrics
      operationId: getMetrics
      responses:
        '200':
          description: Metrics information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ControlMetrics'
  /mode:
    post:
      summary: Force a control mode change
      operationId: setMode
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ModeRequest'
      responses:
        '200':
          description: Mode updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ModeResponse'
        '400':
          description: Invalid request
  /anomaly:
    post:
      summary: Receive anomaly notifications
      operationId: postAnomaly
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AnomalyNotification'
      responses:
        '200':
          description: Acknowledged
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AckResponse'
components:
  schemas:
    OptimizationMode:
      type: string
      enum: [conservative, balanced, aggressive]
    HealthStatus:
      type: object
      properties:
        status:
          type: string
        version:
          type: string
    ControlMetrics:
      type: object
      properties:
        current_mode:
          $ref: '#/components/schemas/OptimizationMode'
        transition_count:
          type: integer
        stability_score:
          type: number
        integral_error:
          type: number
        last_error:
          type: number
        uptime_seconds:
          type: integer
    ModeRequest:
      type: object
      required: [mode]
      properties:
        mode:
          $ref: '#/components/schemas/OptimizationMode'
        reason:
          type: string
    ModeResponse:
      type: object
      properties:
        status:
          type: string
        mode:
          $ref: '#/components/schemas/OptimizationMode'
    AnomalyNotification:
      type: object
      properties:
        anomaly_id:
          type: string
        severity:
          type: string
        metric_name:
          type: string
        current_value:
          type: number
        expected_value:
          type: number
        confidence:
          type: number
        timestamp:
          type: string
    AckResponse:
      type: object
      properties:
        status:
          type: string
        anomaly_id:
          type: string

