
receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      load:
      filesystem:
      network:
      paging:
      process:
        include:
          match_type: regexp
          processes: [".*"]

processors:
  priority_tagger:
    enabled: true
    rules:
      - match: "process.command_line=~/.*java.*/"
        priority: high
      - match: "process.name=~/nginx|httpd/"
        priority: high
      - match: "process.name=~/mysql|postgres|mongodb/"
        priority: critical
      - match: "process.command_line=~/.*python.*/"
        priority: medium
      - match: ".*"
        priority: low
  
  pid_decider:
    controllers:
      - name: coverage_controller
        enabled: true
        kpi_metric_name: aemf_impact_adaptive_topk_resource_coverage_percent_avg_1m
        kpi_target_value: 0.90
        kp: 30
        ki: 5
        kd: 0
        hysteresis_percent: 3
        output_config_patches:
          - target_processor_name: adaptive_topk
            parameter_path: k_value
            change_scale_factor: -20.0
            min_value: 10
            max_value: 60

exporters:
  logging:
    verbosity: detailed

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [priority_tagger]
      exporters: [logging]
    
    control:
      receivers: [hostmetrics]
      processors: [pid_decider]
      exporters: [logging]

