receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      process:
        include:
          match_type: regexp
          processes: [".*"]

processors:
  metric_pipeline:

exporters:
  logging:
    verbosity: detailed
  otlp:
    endpoint: "${env:NEW_RELIC_OTLP_ENDPOINT}"
    headers:
      api-key: "${env:NEW_RELIC_API_KEY}"

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [metric_pipeline]
      exporters: [logging, otlp]
