receivers:
  # Process metrics collection - exclusively focus on process scraper
  hostmetrics:
    collection_interval: 15s  # Slightly longer interval for reduced overhead
    scrapers:
      process:
        include:
          match_type: regexp
          processes: [".*"]  # Collect metrics for all processes
        metrics:
          process.cpu.time: true
          process.memory.rss: true
          process.threads: true

  # Self-metrics collection
  prometheus/self:
    config:
      scrape_configs:
        - job_name: 'phoenix-process-metrics'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8888']
          metrics_path: '/metrics'

processors:
  # Convert cumulative process.cpu.time to delta for better visualization
  cumulativetodelta:
    include:
      match_type: strict
      metrics:
        - process.cpu.time
    max_stale: 15s

  # Batch metrics for efficient export
  batch:
    send_batch_size: 1000
    send_batch_max_size: 2000
    timeout: 5s

  metric_pipeline:

exporters:
  # Detailed logging for development and debugging
  logging:
    verbosity: basic  # Use basic to avoid overwhelming logs
    sampling_initial: 5  # Only log every 5th metric initially
    sampling_thereafter: 100  # Then log every 100th

  # Export to New Relic through OTLP
  otlp:
    endpoint: "${env:NEW_RELIC_OTLP_ENDPOINT}"
    headers:
      api-key: "${env:NEW_RELIC_API_KEY}"
    timeout: 10s
    compression: gzip  # Enable compression to reduce bandwidth usage
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

service:
  pipelines:
    # Main process metrics pipeline
    metrics/process:
      receivers: [hostmetrics]
      processors: [cumulativetodelta, metric_pipeline, batch]
      exporters: [logging, otlp]

    # Self-metrics pipeline to export Phoenix's own metrics
    metrics/phoenix_self:
      receivers: [prometheus/self]
      processors: [metric_pipeline, batch]
      exporters: [otlp]

telemetry:
  metrics:
    address: localhost:8888
  logs:
    level: info
