apiVersion: v2
name: phoenix
description: Phoenix Process Metrics Optimization Platform
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - observability
  - opentelemetry
  - process-metrics
  - optimization
  - cost-reduction
home: https://phoenix.io
sources:
  - https://github.com/phoenix/platform
maintainers:
  - name: Phoenix Team
    email: phoenix@example.com
icon: https://phoenix.io/logo.png

dependencies:
  - name: prometheus
    version: 25.3.1
    repository: https://prometheus-community.github.io/helm-charts
    condition: prometheus.enabled
    
  - name: grafana
    version: 7.0.8
    repository: https://grafana.github.io/helm-charts
    condition: grafana.enabled
    
  - name: postgresql
    version: 13.2.3
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled

annotations:
  category: Monitoring
  licenses: Apache-2.0