id: PID-05
title: "Implement KPI Metric Flapping/Unstable Test"
state: open
priority: medium
created_at: "2025-05-20"
assigned_to: "tester"
area: "test/e2e/pid"
depends_on: []
acceptance:
  - "Test generates rapidly oscillating KPI values around target"
  - "PID controller output is appropriately damped"
  - "Hysteresis settings prevent excessive patch generation"
  - "patch_cooldown_seconds prevents thrashing"
  - "System remains stable despite noisy input"
  - "Logs and metrics show ignored oscillations"
description: |
  KPI metrics in real-world scenarios may be noisy or unstable, rapidly
  oscillating around the target value. This test verifies that the PID
  controller and patch application system can handle such instability
  without themselves becoming unstable.
  
  The test should:
  
  1. Configure a PID controller with target value (e.g., coverage 0.9)
  2. Generate synthetic metrics with deliberate noise and oscillation:
     - KPI value rapidly alternating above and below the target
     - Random noise added to the KPI value
     - Occasional outlier values
  3. Verify controller behavior:
     - Controller output is damped compared to input oscillation
     - Patch generation respects hysteresis_percent setting
     - patches are not generated for changes below threshold
     - Cooldown period prevents patch thrashing
  4. Verify metrics:
     - aemf_pid_input_oscillation_detected_total increments
     - aemf_pid_patch_throttled_total shows patches being limited
  5. Verify system stability:
     - Processor parameter doesn't oscillate with the noisy input
     - Overall system performance remains consistent
  
  This test is essential for ensuring that the adaptive system doesn't
  overreact to normal metric noise, which could lead to system thrashing
  and overall instability.
  
  Implementation should include tests with various oscillation patterns
  and frequencies to validate the system's filtering capabilities. It should
  also verify the impact of different hysteresis and cooldown settings.