id: PIPE-06
title: "Implement Simultaneous Data & Control Pipeline Restart Test"
state: open
priority: high
created_at: "2025-05-20"
assigned_to: "tester"
area: "test/e2e/pipelines"
depends_on: []
acceptance:
  - "Test simulates collector restart under load"
  - "Both data and control pipelines restart successfully without race conditions"
  - "Data flow resumes without data loss"
  - "Control loop re-engages and makes appropriate adjustments if needed"
  - "No deadlocks or panics during startup sequence"
  - "Metrics confirm normal operation after restart"
description: |
  The dual-pipeline architecture of SA-OMF makes restart scenarios more complex,
  as both the data pipeline and control pipeline need to re-establish correctly
  and in the right order. This test verifies that the system can restart gracefully
  under load without race conditions, deadlocks, or data loss.
  
  The test should:
  
  1. Set up a collector with both data and control pipelines enabled
  2. Generate a steady flow of metrics to establish baseline operation
  3. Force a restart of the collector while under load:
     - Use SIGTERM to trigger a graceful shutdown
     - Immediately restart the collector process
     - Alternative: Use a lifecycle hook to restart components internally
  4. Verify system behavior during and after restart:
     - No panics, deadlocks, or unexpected errors
     - Data pipeline resumes processing metrics
     - Control pipeline re-initializes PID controllers
     - Metrics flow continues with minimal interruption
     - Adaptive decisions continue to be made correctly
  5. Perform multiple restart cycles to ensure reliability
  
  This test is important for operational stability, as collectors may need to
  restart in production environments due to updates, configuration changes,
  or system maintenance.
  
  Implementation should include both controlled-environment tests (Docker-based)
  and a Kubernetes test with pod restart to validate real-world behavior.