id: POL-07
title: "Implement Policy with Conflicting PID Output Targets Test"
state: open
priority: high
created_at: "2025-05-20"
assigned_to: "tester"
area: "test/e2e/policy"
depends_on: []
acceptance:
  - "Test configures multiple PID controllers targeting the same processor parameter"
  - "System detects the conflict and follows defined conflict resolution strategy"
  - "Log warnings about conflicting controller targets"
  - "System remains stable without oscillation"
  - "One controller takes precedence according to policy rules"
  - "Conflict detection metrics are emitted"
description: |
  When multiple PID controllers in the policy target the same processor parameter,
  the system needs a clear conflict resolution strategy to prevent oscillation
  and unstable behavior. This test verifies that the system correctly handles
  such conflicts.
  
  The test should:
  
  1. Create a policy.yaml with conflicting controller configurations:
     - Two controllers targeting the same processor parameter (e.g., adaptive_topk.k_value)
     - Different KPI targets for each controller
     - Potentially different PID gains (Kp, Ki, Kd)
  2. Start the collector with this policy
  3. Verify conflict detection and resolution:
     - System logs warnings about conflicting targets
     - One controller takes precedence according to defined rules
       (priority, order in file, most recently added, etc.)
     - aemf_pid_controller_conflict_detected_total metric increments
  4. Generate metrics to trigger controller decisions
  5. Verify system stability:
     - Target parameter doesn't oscillate due to conflicting patches
     - System follows the precedence rules consistently
     - Non-conflicting controllers continue to function normally
  
  This test validates an important aspect of complex control systems where
  multiple adaptation mechanisms might attempt to influence the same parameter.
  
  Implementation should include unit tests for the conflict detection logic
  and integration tests with actual controllers generating patches. Documentation
  should clearly define the conflict resolution strategy implemented.