# Minimal Fallback Template - Please use the full one from spec
optimization_profile: conservative
last_updated: "1970-01-01T00:00:00Z"
trigger_reason: "fallback_template_init"
current_metrics:
  full_ts: 0
  optimized_ts: 0
  experimental_ts: 0
  cost_reduction_ratio: 0.0
config_version: 0
correlation_id: "fallback-init"
last_profile_change_timestamp: "1970-01-01T00:00:00Z" # Renamed from state.transition_timestamp
thresholds: # Renamed from active_thresholds for clarity in template
  conservative_max_ts: 
  aggressive_min_ts: 
pipelines: # Added as per spec
  full_fidelity_enabled: true
  optimized_enabled: true
  experimental_enabled: false
