# Prometheus Configuration for Phoenix
# Simplified working configuration

global:
  scrape_interval: 15s
  evaluation_interval: 30s

rule_files:
  - "/etc/prometheus/rules/*.yml"

scrape_configs:
  # Main collector telemetry
  - job_name: 'otelcol-main'
    static_configs:
      - targets: ['otelcol-main:8888']
    scrape_interval: 30s

  # Main collector optimized output
  - job_name: 'otelcol-main-optimized'
    static_configs:
      - targets: ['otelcol-main:8889']
    scrape_interval: 30s

  # Main collector experimental output  
  - job_name: 'otelcol-main-experimental'
    static_configs:
      - targets: ['otelcol-main:8890']
    scrape_interval: 30s

  # Observer metrics
  - job_name: 'otelcol-observer'
    static_configs:
      - targets: ['otelcol-observer:9888']
    scrape_interval: 15s

  # Control actuator
  - job_name: 'control-actuator'
    static_configs:
      - targets: ['control-actuator-go:8081']
    scrape_interval: 30s

  # Anomaly detector  
  - job_name: 'anomaly-detector'
    static_configs:
      - targets: ['anomaly-detector:8082']
    scrape_interval: 30s

  # Benchmark controller
  - job_name: 'benchmark-controller'
    static_configs:
      - targets: ['benchmark-controller:8083']
    scrape_interval: 30s

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s