# Minimal Prometheus Configuration for Testing
global:
  scrape_interval: 15s
  evaluation_interval: 30s

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']