extensions:
  pic_control:
    policy_file_path: /etc/sa-omf/policy.yaml
    max_patches_per_minute: 3
    patch_cooldown_seconds: 10

receivers:
  hostmetrics:
    collection_interval: 10s
    scrapers:
      cpu:
      memory:
      load:
      filesystem:
      network:
      paging:
      process:
        include:
          match_type: regexp
          processes: [".*"]
  
  # Receiver for self-metrics collection
  prometheus/self:
    config:
      scrape_configs:
        - job_name: 'sa-omf-self'
          scrape_interval: 5s
          static_configs:
            - targets: ['localhost:8888']

processors:
  # Processors will be configured from policy.yaml
  # This separation ensures that dynamic config lives in policy file
  # while pipeline structure lives here

exporters:
  logging:
    verbosity: detailed
  
  prometheusremotewrite:
    endpoint: "http://localhost:9090/api/v1/write"
    timeout: 5s

  pic_connector:
    # PIC connector forwards config patches to pic_control extension

service:
  pipelines:
    metrics:
      receivers: [hostmetrics]
      processors: [priority_tagger, adaptive_topk]
      exporters: [logging, prometheusremotewrite]
    
    control:
      receivers: [prometheus/self]
      processors: [adaptive_pid]
      exporters: [pic_connector]
  
  extensions: [pic_control]

