global_settings:
  autonomy_level: shadow  # Start in shadow mode for safety
  collector_cpu_safety_limit_mcores: 400
  collector_rss_safety_limit_mib: 350

processors_config:
  # Priority tagging configuration
  priority_tagger:
    enabled: true
    rules:
      - match: "process.command_line=~/.*java.*/"
        priority: high
      - match: "process.name=~/nginx|httpd/"
        priority: high
      - match: "process.name=~/mysql|postgres|mongodb/"
        priority: critical
      - match: "process.command_line=~/.*python.*/"
        priority: medium
      - match: ".*"
        priority: low
  
  # Adaptive top-k processor configuration 
  adaptive_topk:
    enabled: true
    k_value: 30
    k_min: 10
    k_max: 60
    resource_field: "process.executable.name"
    counter_field: "process.cpu.utilization"
  
  # Others rollup processor for low-priority processes
  others_rollup:
    enabled: true
    priority_threshold: "low"
    metric_name_prefix: "others"

# Adaptive PID controller configuration
adaptive_pid_config:
  controllers:
    - name: coverage_controller
      enabled: true
      kpi_metric_name: aemf_impact_adaptive_topk_resource_coverage_percent_avg_1m
      kpi_target_value: 0.90
      kp: 30
      ki: 5
      kd: 0
      hysteresis_percent: 3
      integral_windup_limit: 100
      output_config_patches:
        - target_processor_name: adaptive_topk
          parameter_path: k_value
          change_scale_factor: -20.0
          min_value: 10
          max_value: 60

# Safety mode configurations
safety_config:
  safe_mode_processor_configs:
    adaptive_topk:
      k_value: 10
    others_rollup:
      priority_threshold: "critical"

