version: '3.8'

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh:/home/vscode/.ssh:ro
      - ./.zshrc:/home/vscode/.zshrc:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
    environment:
      - GOEXPERIMENT=loopvar
    network_mode: host
    user: vscode
    container_name: phoenix_devcontainer