version: '3'
services:
  # Phoenix OpenTelemetry Collector
  sa-omf-collector:
    image: yourorg/sa-omf-collector:latest
    container_name: sa-omf-collector
    volumes:
      - ../config/config.yaml:/etc/sa-omf/config.yaml
      - ./policy.yaml:/etc/sa-omf/policy.yaml
      - /proc:/proc:ro  # For host metrics access
      - /sys:/sys:ro    # For host metrics access
    ports:
      - "8888:8888"     # Metrics endpoint
      - "13133:13133"   # Health check endpoint
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

  # Prometheus for storing metrics
  prometheus:
    image: prom/prometheus:v2.48.0
    container_name: prometheus
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    restart: unless-stopped
    networks:
      - monitoring

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    volumes:
      - ./docker/grafana/provisioning:/etc/grafana/provisioning
      - ./dashboards:/var/lib/grafana/dashboards
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - monitoring
    depends_on:
      - prometheus

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:
