version: '3.8'

# This compose file is for basic collector execution
# For the full development environment, use the main docker-compose.yml in the root directory

services:
  collector:
    image: sa-omf-otelcol:${TAG:-latest}
    build:
      context: ../..
      dockerfile: deploy/docker/Dockerfile
      args:
        VERSION: ${VERSION:-dev}
        COMMIT: ${COMMIT:-unknown}
        BUILD_DATE: ${BUILD_DATE:-unknown}
    ports:
      - "${PORT_HTTP:-8888}:8888"
      - "${PORT_HEALTH:-13133}:13133"
    volumes:
      - ../../configs/${CONFIG_ENV:-default}:/etc/sa-omf
    command: --config=/etc/sa-omf/config.yaml
    restart: unless-stopped
EOF < /dev/null
