apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"

  - name: NewRelic
    type: prometheus
    access: proxy
    url: https://prometheus-api.newrelic.com
    editable: true
    jsonData:
      httpHeaderName1: 'Api-Key'
      customQueryParameters: 'account=${NEW_RELIC_ACCOUNT_ID}'
    secureJsonData:
      httpHeaderValue1: '${NEW_RELIC_API_KEY}'