# Phoenix v3 Ultimate Process-Metrics Stack - Optimization Mode Control File Template
# Revision 2025-05-22 · v3.0-final-uX
# This file's structure is managed by update-control-file.sh
# It is read by otelcol-main via config_sources to influence pipeline behavior.

optimization_profile: conservative # Default: "conservative", "balanced", or "aggressive"
config_version: 0                # Monotonically increasing counter, bumped by controller
correlation_id: "template-init-cid" # Unique ID for this state, set by controller
last_updated: "1970-01-01T00:00:00Z" # RFC3339 timestamp of last write by controller
trigger_reason: "initial_template_state" # Human-readable reason for the current profile

# Live metrics from Prometheus that led to this decision (snapshot)
current_metrics:
  full_ts: 0              # Active TS count from the full_fidelity pipeline
  optimized_ts: 0         # Active TS count from the optimised pipeline (this drives decisions)
  experimental_ts: 0      # Active TS count from the experimental pipeline
  cost_reduction_ratio: 0.0 # Calculated as 1 - (optimised_ts / full_ts)

# Thresholds currently being used by the controller to make decisions
# These are typically sourced from environment variables by update-control-file.sh
thresholds:
  conservative_max_ts: 15000 # If optimized_ts < this, controller suggests "conservative"
  aggressive_min_ts: 25000   # If optimized_ts > this, controller suggests "aggressive"
  # cost_target_reduction: 0.70 # Informational, from .env (not directly used by otelcol-main)

# Pipeline enablement flags - can be used by otelcol-main's routing logic
# to effectively turn on/off exports or entire processing paths.
pipelines:
  full_fidelity_enabled: true  # Usually always true for baseline comparison
  optimized_enabled: true      # Usually enabled, profile affects its internal behavior
  experimental_enabled: false  # Typically only enabled if profile is "aggressive"

# Timestamp of the last actual *profile change* (e.g. conservative -> balanced)
# Used by the controller script for hysteresis logic.
last_profile_change_timestamp: "1970-01-01T00:00:00Z"

# Optional section for more granular parameters if otelcol-main could use them dynamically.
# For this config-only version, these are mostly for documentation or future use by Go components.
# advanced_phoenix_parameters:
#   target_k_value_for_experimental_topk: 20
#   attribute_stripping_intensity_level: "medium"