id: dependabot
description: "Automated dependency updater"
git_permissions: push
required_checks: []
can_touch:
  - go.mod
  - go.sum
  - .github/dependabot.yml
  - .github/workflows/**
  - deploy/docker/Dockerfile
must_touch: []
blocked_files: []
