name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

# Ensure only one workflow run happens at a time for a given ref
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed for git operations

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache: true

      # Lint code
      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: latest
          args: --timeout=5m

      # Validate configurations
      - name: Validate configurations
        run: |
          bash scripts/validation/validate_policy_schema.sh
          bash scripts/validation/validate_config_schema.sh

      # Build binary
      - name: Build
        run: go build -mod=vendor -o bin/sa-omf-otelcol ./cmd/sa-omf-otelcol

      # Upload artifacts for all branches and PRs
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: bin/sa-omf-otelcol
          retention-days: 7

  # Build and push Docker image for main branch
  docker:
    name: Docker
    runs-on: ubuntu-latest
    needs: [build]
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deploy/docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/sa-omf-collector:latest
            ghcr.io/${{ github.repository_owner }}/sa-omf-collector:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max