name: Phoenix

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 16 * * 1'  # Weekly security scans
  workflow_dispatch:

# This main workflow has been replaced with separate workflows for better organization
# It now serves as a meta-workflow that triggers the individual workflows
# New workflow files:
# - build.yml: Handles building and Docker image creation
# - test.yml: Handles all testing, including unit, integration, and benchmarks
# - pr-validation.yml: Handles PR validation for title format and agent roles

jobs:
  # Dispatch to build workflow
  trigger-build:
    name: Trigger Build Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Build Workflow
        run: |
          echo "Triggering build workflow..."
          # This is a meta-job - actual build happens in build.yml

  # Dispatch to test workflow
  trigger-test:
    name: Trigger Test Workflow
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger Test Workflow
        run: |
          echo "Triggering test workflow..."
          # This is a meta-job - actual testing happens in test.yml

  # Dispatch to PR validation workflow (only for PRs)
  trigger-pr-validation:
    name: Trigger PR Validation Workflow
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Trigger PR Validation Workflow
        run: |
          echo "Triggering PR validation workflow..."
          # This is a meta-job - actual PR validation happens in pr-validation.yml